In [187]:
my_list = [1,2,3]

In [188]:
import numpy as np

In [189]:
my_list

[1, 2, 3]

In [190]:
arr = np.array(my_list)

In [191]:
my_mat = [[1,2,3], [4, 5, 6], [7, 8, 9]]

In [192]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [193]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
np.arange(0,10, 3)

array([0, 3, 6, 9])

In [196]:
arr2 = np.zeros(5)

In [197]:
arr2

array([0., 0., 0., 0., 0.])

In [198]:
np.zeros( (3,2) )

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [199]:
np.ones(4)

array([1., 1., 1., 1.])

In [200]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [201]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [202]:
arr5 = np.eye(3)

In [203]:
np.random.rand(5, 2)

array([[0.75672084, 0.29860072],
       [0.58051061, 0.13098909],
       [0.24821205, 0.44779003],
       [0.50687555, 0.1420371 ],
       [0.49606091, 0.53519015]])

In [204]:
np.random.randn(5)

array([1.39524541, 1.00989126, 0.24771479, 0.81834589, 0.97549151])

In [205]:
np.random.randn(3)

array([-0.99462937, -2.13820219, -0.12560698])

In [206]:
arr4 = np.random.randint(4, 7, (3,3))
arr4

array([[6, 5, 4],
       [5, 5, 4],
       [6, 4, 5]])

In [207]:
arr3 = np.random.randint(10, 100, 15) 
arr3

array([74, 18, 37, 32, 31, 43, 52, 59, 13, 82, 32, 92, 84, 28, 89])

In [208]:
arr4 = arr3.reshape(3,5)
arr4

array([[74, 18, 37, 32, 31],
       [43, 52, 59, 13, 82],
       [32, 92, 84, 28, 89]])

In [209]:
arr4.max()

92

In [210]:
arr4.min()

13

In [211]:
arr3.argmax()
arr3[arr3.argmax()]

92

In [212]:
arr3.shape

(15,)

In [213]:
arr4.shape

(3, 5)

In [214]:
arr3.dtype

dtype('int32')

In [215]:
arr5.dtype

dtype('float64')