In [29]:
import numpy as np

In [30]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[4:8]

array([4, 5, 6, 7])

In [33]:
arr[::3]

array([0, 3, 6, 9])

In [34]:
arr[:5]

array([0, 1, 2, 3, 4])

In [35]:
arr[:5] = -3

arr

array([-3, -3, -3, -3, -3,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_array = arr[:6].copy()
print(slice_of_array)
print(arr) #muda tambem no original 

[-3 -3 -3 -3 -3  5]
[-3 -3 -3 -3 -3  5  6  7  8  9 10]


In [37]:
arr_copy = arr.copy()
arr_copy

array([-3, -3, -3, -3, -3,  5,  6,  7,  8,  9, 10])

In [38]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[1:2,0:2]

array([[20, 25]])

In [40]:
arr_2d[2,1]

40

In [41]:
arr_2d[:2, 1:] #linha 2, coluna 1

array([[10, 15],
       [25, 30]])

In [42]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr<3]

array([1, 2])